using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SonicRoom.Windows.Transport;

/// <summary>
/// Builds the fabricated SDP representing the mediasoup server side of a transport so SIPSorcery's
/// <c>RTCPeerConnection</c> can connect to it. The server never speaks SDP — these strings are
/// synthesized from the <c>create-transport</c> params + codec/consumer info, as mediasoup-client /
/// pymediasoup do.
///
/// The send transport carries MULTIPLE producers (voice, share, mic, file) as separate bundled
/// audio m-lines on one PC. <see cref="BuildSendAnswer"/> emits one <c>a=setup:active</c> section
/// per producer (each repeats the server ICE/DTLS, as pymediasoup does); <see cref="ParseAudioSections"/>
/// reads the mids + payload types SIPSorcery actually assigned in its local offer so the answer matches.
/// </summary>
public static class RemoteSdp
{
    public const string OpusFmtp = "minptime=10;useinbandfec=1;usedtx=0";
    public const int OpusPt = 100;

    public readonly record struct Ext(int Id, string Uri);

    /// <summary>One audio m-section as generated by SIPSorcery's local offer.</summary>
    public readonly record struct AudioSection(string Mid, int PayloadType, int Channels);

    // ---- send answer (multi-producer) ---------------------------------------------------

    public static string BuildSendAnswer(TransportParams p, IReadOnlyList<AudioSection> sections,
        IReadOnlyList<Ext>? extensions = null)
    {
        var sb = SessionHeader(p, sections.Select(s => s.Mid));
        foreach (var s in sections)
        {
            MediaHeader(sb, p, s.PayloadType);
            sb.Append("a=setup:active\r\n");    // remote(server) is DTLS active ⇒ SIPSorcery is DTLS server
            sb.Append($"a=mid:{s.Mid}\r\n");
            sb.Append("a=recvonly\r\n");         // server's view of our sendonly
            Codec(sb, extensions, s.PayloadType, s.Channels);
        }
        return sb.ToString();
    }

    /// <summary>Extract (mid, payloadType, channels) for each audio m-line, in order.</summary>
    public static List<AudioSection> ParseAudioSections(string sdp)
    {
        var sections = new List<AudioSection>();
        var lines = sdp.Split("\r\n", StringSplitOptions.None);
        var inAudio = false;
        var pt = OpusPt;
        var channels = 2;
        string? mid = null;

        void Flush()
        {
            if (inAudio) sections.Add(new AudioSection(mid ?? sections.Count.ToString(), pt, channels));
        }

        foreach (var line in lines)
        {
            if (line.StartsWith("m=", StringComparison.Ordinal))
            {
                Flush();
                inAudio = line.StartsWith("m=audio", StringComparison.Ordinal);
                mid = null; pt = OpusPt; channels = 2;
                if (inAudio)
                {
                    // m=audio <port> <proto> <pt> ...  — take the first payload type.
                    var toks = line.Split(' ');
                    if (toks.Length >= 4 && int.TryParse(toks[3], out var parsed)) pt = parsed;
                }
            }
            else if (inAudio && line.StartsWith("a=mid:", StringComparison.Ordinal))
                mid = line.Substring("a=mid:".Length).Trim();
            else if (inAudio && line.StartsWith($"a=rtpmap:{pt} ", StringComparison.Ordinal))
            {
                // a=rtpmap:100 opus/48000/2
                var slashParts = line.Split('/');
                if (slashParts.Length >= 3 && int.TryParse(slashParts[^1].Trim(), out var ch)) channels = ch;
            }
        }
        Flush();
        return sections;
    }

    // ---- recv offer (one consumer m-line; PT-fallback demuxes the rest) ------------------

    public static string BuildRecvOffer(TransportParams p, RtpParameters consumer,
        string streamId = "sonicroom", string trackId = "consumer",
        IReadOnlyList<Ext>? extensions = null)
    {
        var codec = consumer.Codecs.FirstOrDefault()
            ?? throw new InvalidOperationException("consumer rtpParameters has no codec.");
        var enc = consumer.Encodings?.FirstOrDefault()
            ?? throw new InvalidOperationException("consumer rtpParameters has no encoding/ssrc.");
        var cname = consumer.Rtcp?.Cname ?? "mediasoup";
        var fmtp = FmtpFrom(codec) ?? OpusFmtp;

        var sb = SessionHeader(p, new[] { "0" });
        MediaHeader(sb, p, codec.PayloadType);
        sb.Append("a=setup:actpass\r\n");    // ⇒ SIPSorcery answers active ⇒ DTLS client
        sb.Append("a=mid:0\r\n");
        sb.Append("a=sendonly\r\n");         // server → us
        sb.Append($"a=msid:{streamId} {trackId}\r\n");
        Codec(sb, extensions, codec.PayloadType, codec.Channels ?? 2, fmtp);
        sb.Append($"a=ssrc:{enc.Ssrc} cname:{cname}\r\n");
        return sb.ToString();
    }

    // ---- shared pieces ------------------------------------------------------------------

    private static StringBuilder SessionHeader(TransportParams p, IEnumerable<string> mids)
    {
        var fp = Sha256Fingerprint(p.DtlsParameters);
        var sb = new StringBuilder();
        sb.Append("v=0\r\n");
        sb.Append("o=mediasoup-client 10000 2 IN IP4 0.0.0.0\r\n");
        sb.Append("s=-\r\n");
        sb.Append("t=0 0\r\n");
        if (p.IceParameters.IceLite) sb.Append("a=ice-lite\r\n");
        sb.Append($"a=fingerprint:sha-256 {fp}\r\n");
        sb.Append($"a=group:BUNDLE {string.Join(' ', mids)}\r\n");
        sb.Append("a=msid-semantic: WMS *\r\n");
        return sb;
    }

    private static void MediaHeader(StringBuilder sb, TransportParams p, int pt)
    {
        var fp = Sha256Fingerprint(p.DtlsParameters);
        sb.Append($"m=audio 7 UDP/TLS/RTP/SAVPF {pt}\r\n");
        sb.Append("c=IN IP4 127.0.0.1\r\n");
        sb.Append($"a=ice-ufrag:{p.IceParameters.UsernameFragment}\r\n");
        sb.Append($"a=ice-pwd:{p.IceParameters.Password}\r\n");
        foreach (var c in p.IceCandidates)
        {
            var ip = string.IsNullOrEmpty(c.Ip) ? c.Address : c.Ip;
            sb.Append($"a=candidate:{c.Foundation} 1 {c.Protocol} {c.Priority} {ip} {c.Port} typ {c.Type}\r\n");
        }
        sb.Append("a=end-of-candidates\r\n");
        sb.Append("a=ice-options:renomination\r\n");
        sb.Append($"a=fingerprint:sha-256 {fp}\r\n");
    }

    private static void Codec(StringBuilder sb, IReadOnlyList<Ext>? extensions,
        int pt = OpusPt, int channels = 2, string fmtp = OpusFmtp)
    {
        sb.Append($"a=rtpmap:{pt} opus/48000/{channels}\r\n");
        sb.Append($"a=rtcp-fb:{pt} transport-cc\r\n");
        sb.Append($"a=fmtp:{pt} {fmtp}\r\n");
        if (extensions is not null)
            foreach (var e in extensions)
                sb.Append($"a=extmap:{e.Id} {e.Uri}\r\n");
        sb.Append("a=rtcp-mux\r\n");
        sb.Append("a=rtcp-rsize\r\n");
    }

    private static string Sha256Fingerprint(DtlsParameters d)
    {
        var fp = d.Fingerprints.FirstOrDefault(f =>
                     string.Equals(f.Algorithm, "sha-256", StringComparison.OrdinalIgnoreCase))
                 ?? throw new InvalidOperationException("Server DTLS params have no sha-256 fingerprint.");
        return fp.Value;
    }

    private static string? FmtpFrom(RtpCodecParameters codec)
    {
        if (codec.Parameters is null || codec.Parameters.Count == 0) return null;
        var parts = codec.Parameters.Select(kv => $"{kv.Key}={kv.Value.GetRawText().Trim('"')}");
        return string.Join(";", parts);
    }
}
